//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L2E
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public int HotelId { get; set; }
        public int ConferenceRoomId { get; set; }
        public int CompanyCustomerId { get; set; }
        public int Participants { get; set; }
        public System.DateTime StartDate { get; set; }
        public int Days { get; set; }
    
        public virtual CompanyCustomer CompanyCustomer { get; set; }
        public virtual ConferenceRoom ConferenceRoom { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
