//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L2E
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Id { get; set; }
        public int HotelId { get; set; }
        public decimal Price1 { get; set; }
        public System.DateTime ActiveFrom { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
